dt = 0.05
iterations = 4

[[galaxies]]
num_bodies = 10_000
size = 100.0
center_mass = 4e4
position_x = -100.0
position_y = -100.0
velocity_x = 0.0
velocity_y = 3.0

[[galaxies]]
num_bodies = 10_000
size = 100.0
center_mass = 4e4
position_x = 100.0
position_y = 100.0
velocity_x = 0.0
velocity_y = -3.0